### ISSUE TITLE
Undo/Rollback draft changes partially or completely and/or reset draft to live version

### ISSUE THREAD

**Issue by timashev** [apostrophecms/apostrophe-workflow#130]
When using Apostrophe CMS with Apostrophe Workflow it seems there is no way **either** to cancel editing and rollback draft of the page/document/piece to its live version **or** to undo the last change only (like Cmd/Ctrl-Z). Maybe I just didn't find/discover this function, but in production I'm constantly finding myself in a situation when I made a wrong change (like accidentally deleting a widget from the area or overwriting the translated text by the export from 'Default' locale) and cannot simply undo it (or reset draft to the live version at the least). Would be nice to have this feature added or documented (if it's present already).

**Comment by boutell** [comment]
Good point. It's a bit odd that the history modal allows you to reapply the changes in a commit but not actually revert to it. You can use the classic Apostrophe "versions" feature, but that isn't synced up to the commit history, the snapshots are much more arbitrary.

**Comment by timashev** [comment]
First, I would suggest to add the possibility to cancel changes made to `draft` version by making it identical to `live` version (i.e. full reset of the draft). This is kind of a reverse action to Commit & Export :) If I don't want to Commit and Export, then I need to be able to Drop the changes at least.

Full-featured undo/redo is not necessary IMO.

Second: The other good thing would be to be able to DROP (not simply dismiss) the Submission. E.g., if I submit the changes, I can see the Submission in the Workflow, but the only options there are to commit the changes or to dismiss the submission itself (not the changes). It would be nice to have an option to DROP/CANCEL the submission with all its changes.

This will let the user to submit unwanted changes and then just drop them from the Workflow window. Not a direct way, but also OK.

**Comment by boutell** [comment]
The ability to revert to a specific commit was added.
