### ISSUE TITLE
Workflow [draft/live] dropdown on checkbox fields prevents you from selecting an option

### ISSUE THREAD

**Issue by snetErz** [apostrophecms/apostrophe-workflow#135]
When you try to select an option in a checkbox field list the dropdown is taking focus instead of the checkbox input field. I believe the label is targeting the next form field type and focusing on that. The solution would be to use for/id attributes or reorder the dropdown for workflow draft/live to after the checkbox input field in the html.

**From:**
```html
<label class="apos-form-checkbox-label apos-text-small">
    <span class="apos-workflow-field-controls"><select class="apos-workflow-field-state-control" data-apos-workflow-field-state-control=""><option value="draft" selected="">Draft</option><option value="live">Live</option></select></span>
    <input class="apos-form-checkbox-input" name="fieldExample" value="Option Example" type="checkbox">
    <span class="apos-form-checkbox-indicator"></span>
    Option Example
</label>
```

**To:**

```html
<label class="apos-form-checkbox-label apos-text-small">
    <input class="apos-form-checkbox-input" name="fieldExample" value="Option Example" type="checkbox">
    <span class="apos-form-checkbox-indicator"></span>
    Option Example
    <span class="apos-workflow-field-controls"><select class="apos-workflow-field-state-control" data-apos-workflow-field-state-control=""><option value="draft" selected="">Draft</option><option value="live">Live</option></select></span>
</label>
```

Moving the dropdown seems to fix the issue for me.

Visual Sample:
The first field I fixed in inspector, the second one is the default layout, and you can see that it focused on the dropdown instead of the checkbox input field.

<img width="553" alt="screen shot 2018-01-23 at 9 27 39 am" src="https://user-images.githubusercontent.com/7535419/35287553-d4596ff4-001f-11e8-9bec-6a13417472f2.png">

**Comment by boutell** [comment]
This got fixed.
