### ISSUE TITLE
Pages and pieces not visible on DRAFT MODE

### ISSUE THREAD

**Issue by dcramirezo-aesop** [apostrophecms/apostrophe-workflow#164]
I'm having issues when trying to configure Apostrophe Workflow on my site. After running

```
node app apostrophe-workflow:add-missing-locales --live
node app apostrophe-workflow:remove-numbered-parked-page
node app apostrophe-workflow:harmonize-workflow-guids-by-parked-id
```

I need to use this module only for approvals., as the site has pieces created to work as articles to create templates, which are managed by various people in the team. I used to have some page types that have been used as page templates.

A the moment, workflow is working for a few pages including home and trash as well as some custom page types. This means, all pages and pieces are visible on **LIVE MODE**, but some pages and all pieces are not in **DRAFT MODE**. It’s like if they didn’t exits at all. Checking on the DB, pages that are not visible have the `“workflowLocale”: “default”`, whereas the one page visible on both modes doesn’t have either.
Pieces don’t have any information related to workflow.

Also, when trying to access any piece in **DRAFT MODE**, I’m getting the following error:

```
if (locale.match(/-draft$/)) {
          ^

TypeError: Cannot read property 'match' of undefined
    at Object.self.draftify (/Users/../../node_modules/apostrophe-workflow/lib/api.js:566:15)
    at getTwo (/Users/../../node_modules/apostrophe-workflow/lib/api.js:272:70)
    at /Users/../../node_modules/apostrophe-workflow/node_modules/async/lib/async.js:718:13
    at iterate (/Users/../../node_modules/apostrophe-workflow/node_modules/async/lib/async.js:262:13)
    at /Users/../../node_modules/apostrophe-workflow/node_modules/async/lib/async.js:274:29
    at /Users/../../node_modules/apostrophe-workflow/node_modules/async/lib/async.js:44:16
    at /Users/../../node_modules/apostrophe-workflow/node_modules/async/lib/async.js:723:17
    at /Users/../../node_modules/apostrophe-workflow/node_modules/async/lib/async.js:167:37
    at /Users/../../node_modules/apostrophe-workflow/lib/api.js:268:16
    at /Users/../../node_modules/apostrophe/lib/modules/apostrophe-docs/lib/cursor.js:1086:18
    at /Users/../../node_modules/apostrophe/node_modules/async/lib/async.js:52:16
    at /Users/../../node_modules/apostrophe/node_modules/async/lib/async.js:1209:30
    at /Users/../../node_modules/apostrophe/lib/modules/apostrophe-docs/lib/cursor.js:1367:18
    at /Users/../../node_modules/apostrophe/node_modules/async/lib/async.js:52:16
    at /Users/../../node_modules/apostrophe/node_modules/async/lib/async.js:269:32
    at /Users/../../node_modules/apostrophe/node_modules/async/lib/async.js:44:16
    at /Users/../../node_modules/apostrophe/node_modules/async/lib/async.js:52:16
    at iterate (/Users/../../node_modules/apostrophe/node_modules/async/lib/async.js:260:24)
    at Object.async.forEachOfSeries.async.eachOfSeries (/Users/../../node_modules/apostrophe/node_modules/async/lib/async.js:281:9)
    at Object.async.forEachSeries.async.eachSeries (/Users/../../node_modules/apostrophe/node_modules/async/lib/async.js:214:22)
    at after (/Users/../../node_modules/apostrophe/lib/modules/apostrophe-areas/lib/cursor.js:89:22)
    at self.afters.(anonymous function) (/Users/../../node_modules/apostrophe/lib/modules/apostrophe-docs/lib/cursor.js:170:18)
```
Not sure if the issue above is due to parked pages. My issue is that some types of page have been used as template for the creation of various pages, in my case more than 10 pages already created. The documentation is not very clear on how to park all those pages pages (https://apostrophecms.org/docs/modules/apostrophe-pages/index.html#park), especially when there are more than one page created from a single type (https://apostrophecms.org/docs/tutorials/howtos/search.html)

Will the **parkedId** work for all those pages or is this functionality for an only specific page of an specific type?

Does anyone know how to fix this? 
Thanks D

**Comment by dcramirezo-aesop** [comment]
Hi Tom!
Please find a link to my branch in github that includes the code after making updates on Apostrophe and Workflow installation. Maybe that's where the issues begin as I tried to installed workflow is a old version of apostrophe. Then updated Apostrophe and many of the required packages. After that, continue to follow the configuration instructions for apostrophe workflow. That will be it!

`https://github.com/aesop/aln-email-layout-tool/tree/ALN-0318`

Since them, everything that I describe above is happening. I'm also getting that same "match" error, when in **LIVE MODE** and visiting any piece. On the console, I'm getting  the following error as well:

```
user.js:10 Uncaught TypeError: Cannot read property 'workflowLocale' of undefined
    at self.beforePopulate (user.js:10)
    at wrapper (lodash.js:3592)
    at async.js:718
    at iterate (async.js:262)
    at async.forEachOfSeries.async.eachOfSeries (async.js:281)
    at _parallel (async.js:717)
    at Object.async.series (async.js:739)
    at Object.self.populate (user.js:24)
    at Object.self.play (always.js:14)
    at HTMLDivElement.enhance (always.js:56)
```

which what I described I didn't find on the DB. There is a copy of the test DB on that branch as well.

I really appreciate if you could help me with this. 
Thanks!
D

**Comment by dcramirezo-aesop** [comment]
I have fixed the error for pages and pieces, as they were in the trash. However, I'm still having that issues with the images. There are some in only `-draft` mode, others have the `default` and `default-draft` mode on DB. But still If I add various images to the pieces, some are visible on either draft or Live view but not both! 
Even realised that some of the pieces joined with other pieces.
@boutell  Any suggestions with this?

**Comment by boutell** [comment]
If a document was created in draft mode and has never been "committed" to push it to live mode then it may very well be appropriate for it not to be visible yet in "live" mode. Thus "still in the trash" in live mode.

I would recommend that you start with our apostrophe-enterprise-testbed project, in which workflow is working properly. That project's README also has a series of test steps for a person to follow in testing the site, which will walk you through workflow as it is meant to be used:

https://github.com/apostrophecms/apostrophe-enterprise-testbed

You can use that "known good" project as a starting point to recreate the configuration you're having problems with.

Or, we could talk about an enterprise support engagement. That would allow us to commit some hours to working directly on your project and helping you achieve exactly the results you want. If you'd like to pursue that, please reach out to support@punkave.com.

The github URL you sent me is 404'ing for me. I think it might be a private repo, which is probably appropriate since it is your private project, yes?

Closing this for now for housekeeping, because it sounds like something that would need to be an enterprise engagement in its current form, but if you find a way to reproduce these problems in the enterprise sandbox or a branch of it and can provide steps to reproduce a specific issue we can of course take a look.

Thanks!
