### ISSUE TITLE
Should start out in draft mode

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe-workflow#174]
Live mode is pretty much for previewing. Start people out where they can work and are not confused about not being able to edit yet. Stuart-approved idea.

**Comment by waynehaffenden** [comment]
Was this ever implemented or a config value to make draft mode the default?

**Comment by boutell** [comment]
Not so far, no.

**Comment by jogarijo** [comment]
I've been using a dirty hack to achieve this, namely having a middleware in `apostrophe-express` that detects when the user logs in, and forcefully set `req.session.workflowMode` to `draft` then.

After a quick look in `apostrophe-workflow` source, the fix seems quite straightforward. I can open a PR to make it configurable if this change is still wanted.

**Comment by jogarijo** [comment]
@boutell I took the liberty to open a pull request for that. I hope it's ok with you!
See here: https://github.com/apostrophecms/apostrophe-workflow/pull/301

**Comment by boutell** [comment]
Thanks again! This went out yesterday.
