### ISSUE TITLE
Commit issue in widgets with Array Joins

### ISSUE THREAD

**Issue by manoj-krishnan** [apostrophecms/apostrophe-workflow#178]
Hello, I found an issue when trying to commit widgets which involve array joins. The `resolveRelationships` method in the apostrophe-workflow's API is corrupting relationships when saving the commit.

I narrowed down the issue to line no. 138 within the [api.js](https://github.com/apostrophecms/apostrophe-workflow/blob/master/lib/api.js) (inside the `remapDocs` method). The `secondLocaleIds` calculation in there seems to be redundant since that value seems to be getting calculated on line 113 (in the previous method in that async chain).

The problem seems to stem from the fact that this second calculation of `secondLocaleIds` seems to refer to the var `originalIds` (which belongs to the parent scope - the `mapJoins` method). The `originalIds` variable gets mutated when there is more than one join being processed in a commit since each join is getting processed asynchronously. 

While this operation should just figure out the `_id` of a specific doc in the live locale, given an `_id` of the same doc from the draft locale, it's returning the `_id` for a different doc since the input `_id` is messed up, which is causing the `oldIdToNewId` mapping to break. As a result, this issue is causing the `pieceIds` property in the parent doc to be set to `null` instead of the `_id` value of the content from the live locale, which ends up breaking the view-render in live mode (the widget renders properly in draft mode).

I'll push a branch which reproduces this issue to the apostrophe-enterprise-testbed repository shortly and update this thread. I'll also update this thread with a PR which I hope will fix this issue. Please review/validate this issue/fix and let me know if I've missed something.

**Comment by manoj-krishnan** [comment]
[PR #24](https://github.com/apostrophecms/apostrophe-enterprise-testbed/pull/24) in the apostrophe-enterprise-testbed is capable of reproducing this issue.

**Comment by boutell** [comment]
Hi Manoj, I am unable to reproduce this issue following your instructions. It doesn't seem to matter if I export or not, I can still see the images in live mode afterwards.

Is there any chance your package-lock.json is stuck on version 2.7.3 or earlier? In version 2.7.4 we fixed a bug much like this.

**Comment by boutell** [comment]
(Apologies for the holdup in my response. We had to prioritize an enterprise customer with a major launch this week.)

**Comment by manoj-krishnan** [comment]
@boutell Tom, you were right. Your fix (in version 2.7.4) where you've updated the `mapJoins` method to use an `async.series` instead of `async.eachLimit` to map the joins seems to have been done to specifically fix this race condition which I seem to have hit. Guess it _is_ our version not being up-to-date that caused the issue. Can't believe it didn't occur to me to check with an updated version of workflow :D I'm closing this one out. Thanks for the review!

**Comment by boutell** [comment]
Glad that worked out!
