### ISSUE TITLE
Labeling

### ISSUE THREAD

**Issue by abea** [apostrophecms/apostrophe-workflow#188]
It takes more space, but "Submit" and "Commit" seem too terse to be very clear. I'd suggest even a small change to "Submit Changes" and "Commit Changes." Or "Drafts" since that terminology is used elsewhere. For a new user it could be confusing what they're submitting or committing.

"Commit" also does feel technical to me. Was "Publish" considered as an alternative?

**Comment by bobclewell** [comment]
+1 
I've been in workflow a little lately and I agree. Some ideas on renaming... "Submit draft" v "Commit to live" ...or maybe "Submit draft" v "Publish live" ...or maybe just "Submit" and "Publish" would be a better pair. I really like the idea of "Publish" rather than "Commit" since that is common in similar CMS platforms.

cc: @carlykaras @stuartromanek thoughts?

**Comment by abea** [comment]
Good ideas. I'd still avoid single word labels here. There's enough complexity that a second word increases clarity greatly.

**Comment by stuartromanek** [comment]
Very much in favor of longer but clearer UI for Workflow, as it already is complex

**Comment by boutell** [comment]
Adding "changes" is fine. Submit really does mean submit- for somebody else
to review and maybe commit. Commit means copy this document over from the
draft locale to the live locale people can see.

Semantic land mine to ponder: "publish" is already a thing in plain
Apostrophe and means something different.

**Comment by abea** [comment]
This is where the object of the sentence is so important. "Publish" is already a thing in terms of the piece/page/whatever. "Publish changes" specifies that the changes are what we're acting on. Maybe "publish" isn't right in case these are non-published docs that are being changed, though. "Commit changes" might be enough.

I'm also interested in @carlykaras or other non-dev thoughts as well.

**Comment by carlykaras** [comment]
Agreed that we want to keep this separate from Publish for UI consistency. Commit is definitely on the technical end of the adjective spectrum, so I would try to change that if we can. I do like "Submit Draft" .
