### ISSUE TITLE
There should be a way to remove workflow

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe-workflow#216]
Such a command line task would have to come with a dire warning, of course, that you are losing all of your localized content. A requirement to pick the locale you are keeping, if you have more than one. And a choice whether to keep draft or live.

Also a reminder to the user that they must remove the workflow module immediately after running the task.

**Comment by abea** [comment]
This was added https://github.com/apostrophecms/apostrophe-workflow#removing-workflow-from-a-project
