### ISSUE TITLE
localization._url should include apos.prefix

### ISSUE THREAD

**Issue by sepastian** [apostrophecms/apostrophe-workflow#246]
The frontend locale switcher described [in the docs](https://github.com/apostrophecms/apostrophe-workflow#building-a-locale-picker-on-the-front-end) generates faulty URLs, if `apos.prefix` exists, by not taking into account `apos.prefix`.

As far as I understand, these URLs are generated [here](https://github.com/apostrophecms/apostrophe-workflow/blob/master/lib/api.js#L1045). Take `apos.prefix` into account when generating URLs.

**Comment by sepastian** [comment]
As a workaround, I am currently using this to set the URLs to `apos.prefix + localization.slug`.

```
<ul class="language-selector">
  <li class="locale">{{ __("Sprache") }}</li>
  {% for l in apos.workflow.localizations() %}
    {% set country =  l.workflowLocale.split('-')[0] %}
    {% set url = apos.prefix + l.slug %}
    <li class="locale">
      <a href="{{ url }}">
        <span>{{ l.label }}</span>
      </a>
    </li>
  {% endfor %}
</ul>
```

**Comment by boutell** [comment]
See #247, thanks.
