### ISSUE TITLE
server crashes when editor clicks on "commit" in workflow

### ISSUE THREAD

**Issue by reykjavikingur** [apostrophecms/apostrophe-workflow#254]
My Apostrophe server crashes with the following error:

```
/path/to/my-apostrophe-app/node_modules/apostrophe-workflow/lib/routes.js:543
        var module = self.apos.docs.getManager(draft.type);
                                                     ^

TypeError: Cannot read property 'type' of undefined
```

This happens when a user with "editor" permissions (see below) opens the Workflow panel and without selecting a page, clicks on one of the "commit" links. I'm surprised that such users are able to see and click those links, but I'm much more surprised that the workflow module crashes the server if they do.

STEPS TO RECREATE:

Here is my workflow config in `app.js`:

```

        'apostrophe-workflow': {
            locales: [
                {
                    name: 'default',
                    label: 'Default',
                },
            ],
            defaultLocale: 'default',
            alias: 'workflow',
        },

        'apostrophe-workflow-modified-documents': {},

```

I started with `lib/modules/apostrophe-users/index.js` having:
```
module.exports = {
    groups: [
        {
            title: 'admin',
            permissions: ['admin']
        }
    ]
};
```
but after my first time logging in as "admin", I commented out those groups and restarted the app, so I could edit them in the admin interface.

As an "admin" user, I created an editor group with the following permissions:

* Editor
  * Default: Edit
* View Private Locales
* Upload & Crop
* Edit: Global
  * Default: Edit
* Edit: Pages
  * Default: Edit
* Edit: Image
  * Default: Edit
* Edit: File
  * Default: Edit
* Edit: Document
  * Default: Edit

Then as "admin" I created a user with the "editor" group. I logged in as that editor user, switched to draft mode, confirmed that I can submit (but not commit) changes to the home page. But then when I open the "Workflow" menu and select "Manage", I can see the "commit" link on the far right, and when I click on it, the server crashes with the error noted above.

I'm on `apostrophe@2.92.1` and `apostrophe-workflow@2.22.0`.

**Comment by reykjavikingur** [comment]
@boutell @bgantick Do you think it will be possible to receive some assistance with this issue?

**Comment by boutell** [comment]
Clearly it needs attention. BTW are you with one of our Enterprise clients?
Not a requirement for progress to be made, just good to know.

**Comment by reykjavikingur** [comment]
Hi @boutell and thanks for responding quickly. We're not an Enterprise client at this time. I tried for a while to work around the problem, but even after reverting to minimal configurations as described above, permissions in the workflow were fundamentally broken. The workflow module is rather complex, so before I attempted to fix it myself, I hope to get your assessment, as that will save me time and probably benefit your other users more quickly.

**Comment by bmauger** [comment]
@boutell - I'm a colleague of @reykjavikingur, any idea when your team will look into this? It's become a bit of a blocker for us. Thanks so much!

**Comment by boutell** [comment]
Hi @bmauger and @reykjavikingur, as you can see a PR for this is working its way through. Thanks for reporting the issue!

In case you have urgent needs in the future I would encourage you to check out enterprise support as well:

https://apostrophecms.org/support/enterprise-support

**Comment by boutell** [comment]
For housekeeping, I'm closing this in favor of the PR, which now represents the status of the fix.

**Comment by reykjavikingur** [comment]
Thank you @boutell . I also see PR's for some of the related issues. That's great to see. Apostrophe has been an excellent solution as a lightweight (but highly configurable) CMS.
