### ISSUE TITLE
Apostrophe CMS Editor role “commit” and “submit” functionality

### ISSUE THREAD

**Issue by bmauger** [apostrophecms/apostrophe-workflow#256]
I have set up the Editor role in Groups and assigned it with the permissions shown in the attached image. I then created a user and assigned the user to the Editor group.

Next, I chose a page and assigned it to Editors. So far, so good. However, when I log in as my Editor user and make a change to a page, I don't see the "commit" or "submit" buttons at the bottom of the window (as is seen when logged in as Admin). Also, if I try to submit the page via _Workflow_ > _Manage_, I see both "Submit" and "Commit" although "Commit" doesn't actually commit the changes. I would expect to see [only] "Submit" at the bottom of the window as well as [only] "Submit" in the available selections of the dropdown in the _Workflow_ > _Manage_ window.

Needless to say, I'm confused by this odd behavior. Any thoughts or direction would be appreciated. I'm using `apostrophe@2.92.1` and `apostrophe-workflow@2.22.0` .

![image](https://user-images.githubusercontent.com/10211877/62550214-de12d900-b837-11e9-9c6a-7d5018a48878.png)

**Comment by boutell** [comment]
Fixed in #259, closing in favor of that PR, watch the PR for updates. Thanks for the report!
