### ISSUE TITLE
Language switcher should preserve query string

### ISSUE THREAD

**Issue by ericwong3** [apostrophecms/apostrophe-workflow#270]
As title mentions. If I am on say `/artists?tags=french` and click the link generated from `{{ localization._url | build({ workflowLocale: localization.workflowLocale }) }}`, the `?tags=french` portion will be dropped. It should be preserved.

**Comment by boutell** [comment]
Try passing it data.url instead.

**Comment by boutell** [comment]
People translate tags though so this might not work out like you're hoping.
Joins are better than tags for i18n projects.

**Comment by ericwong3** [comment]
You mean like this?
```
{% for localization in apos.workflow.localizations() %}
  <li><a href="{{ data.url|build({ workflowLocale: localization.workflowLocale }) }}">{{ localization.label }}</a></li>
{% endfor %}
```
Does not seem to work..
I can manually simulate by navigating to `http://localhost:3000/en/?workflowLocale=zh-cn` and I will get 302 back to `http://localhost:3000/en/`

For your suggestion, yeah I read it on the README suggesting the use of joins for translation. The `tags` is just an example (as it is a built-in attribute), for my case it is a boolean filter, like `?featured=1`, so the focus is filter param got dropped.
