### ISSUE TITLE
MongoDB 4.4 is currently incompatible with apostrophe-workflow

### ISSUE THREAD

**Issue by breyell** [apostrophecms/apostrophe-workflow#326]
## To Reproduce

Step by step instructions to reproduce the behavior:

> 1. Use MongoDB version 4.4.0
> 2. Try to view a list of pieces in the admin menu
> 3. See Error

```bash
MongoError: Path collision at workflowLastCommitted.at remaining portion at at MessageStream.messageHandler
```

## Expected behavior
> Previous piece entries should show in admin menu

## Describe the bug
> No previously entered pieces show in admin area

## Details
Looks like this is due to a [compatibility change in MongoDB 4.4](https://docs.mongodb.com/manual/release-notes/4.4-compatibility/#path-collision-restrictions)

**Version of Node.js:**
v12.16.1

**Server Operating System:**
macOS 10.15.6

**Additional context:**
> Add any other context about the problem here. If the problem is specific to a browser, OS or mobile device, specify which.

**Comment by boutell** [comment]
See PR on apostrophe: https://github.com/apostrophecms/apostrophe/pull/2310
