### ISSUE TITLE
Cannot update/insert a piece with admin-piece permissions

### ISSUE THREAD

**Issue by ecb34** [apostrophecms/apostrophe-workflow#332]
## To Reproduce

Step by step instructions to reproduce the behavior:

> 1. Login with guest user (have admin-project and edit permissions)
> 2. Go to live mode
> 3. Go to localhost:3000/de/projects
> 4. Click on approve/decline
> 5. You will see the notification Error.Try again, there was an error when updating

## Expected behavior
> The project should be updated

## Describe the bug
> When installing apostrophe-workflow the admin-project permission is not working, you cannot see on the admin modal the project or insert/update the piece. The findForEditing function is also not working

I attach a sample project

[apostrophe-boilerplate.tar.gz](https://github.com/apostrophecms/apostrophe-workflow/files/6027878/apostrophe-boilerplate.tar.gz)

**Comment by boutell** [comment]
Have you granted the "view-private-locales" permission?

**Comment by ecb34** [comment]
With view private locale and commit permissions for the locale works fine.
