### ISSUE TITLE
[DOCS ISSUE] Page: How do I create a 404 Not Found page?

### ISSUE THREAD

**Issue by jansensan** [apostrophecms/apostrophe-workflow#334]
This is relative to the documentation on [https://docs.apostrophecms.org/](https://docs.apostrophecms.org/howtos/how-do-i-create-a-404-not-found-page.html#how-do-i-create-a-404-not-found-page), but most likely relates to this project.

For projects with apostrophe-workflow, the instructions linked above lead back to the login page when an actual 404 occurs:

- <https://sportlogiq.com/en/whatever>
- <https://www.vkitech.com/en/whatever>
- <https://arts-et-medias.net/en/whatever>

Either there is a bug (maybe? not sure) or there is some additional documentation required to clarify how to ensure that an actual 404 presents the 404 template.

**Comment by abea** [comment]
You linked to the 404 page documentation. Are you saying that with Apostrophe Workflow the 404 redirect leads to the login page instead of the 404 page?

**Comment by jansensan** [comment]
Indeed. All those sites show the proper 404 template if the user is logged in, but if you go to those URLs above as anon, you get the login page.

Come to think of it, they all have apostrophe-second-chance-login installed. So the issue is really to know how to properly set whichever component is responsible for this (starting to think it's second-chance, thus the issue is in the wrong repo).

**Comment by jansensan** [comment]
Issue opened in appropriate repo instead: https://github.com/apostrophecms/apostrophe-second-chance-login/issues/2
